version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    executor: node/default
    steps:
      - run: echo "test"

workflows:
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
